// ─────────────────────────────────────────────────────────────────────────────
// DEMO / SCAFFOLD DATA for the Intelligence & Reports hub (/reports).
//
// ⚠️  EVERYTHING in this file is PLACEHOLDER data used only to build and preview
//     the reporting surface. It is NOT real intelligence. No quote here is a real
//     statement by a real person — speakers are anonymized role labels
//     ("Resident · Kongowea"), never named individuals, and opponent figures are
//     illustrative, not measured.
//
// When real ingestion is wired (WhatsApp intake, Meta/TikTok tokens, a social
// listening feed), replace these exports with data fetched from those sources.
// The page reads ONLY from these named exports, so the swap is mechanical.
// ─────────────────────────────────────────────────────────────────────────────

export type Sentiment = 'praise' | 'neutral' | 'criticism';
export type Source = 'whatsapp' | 'facebook' | 'tiktok' | 'instagram' | 'x' | 'field';

export interface SentimentSplit {
  praise: number;
  neutral: number;
  criticism: number;
}

// Rolling window headline numbers (last 7 days, illustrative).
export const OVERVIEW = {
  windowLabel: 'Last 7 days',
  totalMentions: 1284,
  reach: 96400,
  sentiment: { praise: 612, neutral: 431, criticism: 241 } as SentimentSplit,
  // Direction vs the previous window.
  trend: { mentions: +18, praise: +6, criticism: -3 }, // percentage points / %
};

// The AI executive brief — in production this is generated by the Claude API from
// the week's collected text. Here it's a representative sample so admins can see
// the shape of the deliverable.
export const EXECUTIVE_BRIEF: string[] = [
  'Conversation about Alfayo rose ~18% this week, driven mostly by ground activity in Kongowea and Mkomani. Overall tone stays net-positive (praise outweighs criticism roughly 2.5 : 1).',
  'Strongest praise themes: youth programs and visible presence at community events. People repeatedly contrast "he shows up" against opponents seen as absent.',
  'Main complaint cluster: water and drainage in parts of Ziwa La Ng’ombe and Frere Town. This is the single biggest driver of negative sentiment and is worth a targeted response.',
  'Opponent watch: SAIDO is generating the most counter-conversation, mostly around development promises. AA and Dekow remain low-volume this week.',
  'One national thread affecting Mombasa (port / jobs debate) is spilling into local chatter — monitor for the next 72 hours.',
];

// Time-boxed alerts an admin should action.
export interface Alert {
  id: string;
  level: 'high' | 'medium' | 'info';
  title: string;
  detail: string;
  where: string;
  when: string;
}

export const ALERTS: Alert[] = [
  { id: 'a1', level: 'high',   title: 'Water complaint spike', detail: 'Cluster of complaints about water supply gaining traction; risk of becoming an opponent talking point.', where: 'Ziwa La Ng’ombe', when: '2h ago' },
  { id: 'a2', level: 'medium', title: 'Opponent claim to rebut', detail: 'A development-promise claim by an opponent is circulating; consider a factual response.', where: 'Kongowea', when: '5h ago' },
  { id: 'a3', level: 'info',   title: 'Praise wave', detail: 'Positive reactions after the youth event; good moment to amplify.', where: 'Mkomani', when: '1d ago' },
];

// The debate — themes people are actually discussing, split praise vs complaint.
export interface Theme {
  label: string;
  volume: number;         // share of conversation (relative units)
  sentiment: Sentiment;
}

export const PRAISE_THEMES: Theme[] = [
  { label: 'Shows up / visible on the ground', volume: 88, sentiment: 'praise' },
  { label: 'Youth programs & jobs',            volume: 71, sentiment: 'praise' },
  { label: 'Accessible / approachable',        volume: 54, sentiment: 'praise' },
  { label: 'Supports women’s groups',      volume: 43, sentiment: 'praise' },
];

export const COMPLAINT_THEMES: Theme[] = [
  { label: 'Water & drainage',        volume: 62, sentiment: 'criticism' },
  { label: 'Roads in the interior',   volume: 38, sentiment: 'criticism' },
  { label: 'Youth unemployment',      volume: 29, sentiment: 'criticism' },
  { label: 'Wants more town-halls',   volume: 17, sentiment: 'criticism' },
];

// Where the conversation is hot — per-ward praise vs complaint (illustrative).
export interface WardMood {
  ward: string;
  praise: number;
  criticism: number;
}

export const WARD_MOOD: WardMood[] = [
  { ward: 'Kongowea',          praise: 74, criticism: 26 },
  { ward: 'Mkomani',           praise: 69, criticism: 31 },
  { ward: 'Kadzandani',        praise: 61, criticism: 39 },
  { ward: 'Frere Town',        praise: 55, criticism: 45 },
  { ward: 'Ziwa La Ng’ombe', praise: 48, criticism: 52 },
];

// The voices feed — anonymized sample "mentions". Role labels only, never names.
export interface Voice {
  id: string;
  source: Source;
  speaker: string;      // anonymized role, e.g. "Boda rider · Nyali"
  sentiment: Sentiment;
  text: string;
  topic: string;
  when: string;
}

export const VOICES: Voice[] = [
  { id: 'v1', source: 'whatsapp', speaker: 'Resident · Kongowea',        sentiment: 'praise',    text: 'He was here again for the cleanup. At least this one we see him.', topic: 'Presence', when: '1h' },
  { id: 'v2', source: 'facebook', speaker: 'Community member · Mkomani', sentiment: 'praise',    text: 'The youth program is actually helping some of our boys get work.', topic: 'Youth jobs', when: '3h' },
  { id: 'v3', source: 'tiktok',   speaker: 'Viewer',                     sentiment: 'neutral',   text: 'Let us wait and see what all of them will do, not just talk.', topic: 'General', when: '4h' },
  { id: 'v4', source: 'whatsapp', speaker: 'Resident · Ziwa La Ng’ombe', sentiment: 'criticism', text: 'Water is still a problem here. We need action not photos.', topic: 'Water', when: '5h' },
  { id: 'v5', source: 'instagram',speaker: 'Follower',                   sentiment: 'praise',    text: 'Respect for supporting the women’s table-banking group.', topic: 'Women groups', when: '7h' },
  { id: 'v6', source: 'facebook', speaker: 'Resident · Frere Town',      sentiment: 'criticism', text: 'The road to the interior is bad. Whoever fixes it gets my vote.', topic: 'Roads', when: '9h' },
];

// What our own network is reporting from the field (members / Warembo / Flames /
// community leaders / chiefs). In production this is fed by consenting members via
// the in-app intake, not by scraping anyone's private chats.
export interface NetworkNote {
  id: string;
  circle: 'Members' | 'Warembo' | 'Alfayo Flames' | 'Community leaders' | 'Chiefs';
  area: string;
  mood: Sentiment;
  note: string;
  when: string;
}

export const NETWORK_NOTES: NetworkNote[] = [
  { id: 'n1', circle: 'Chiefs',            area: 'Kongowea',          mood: 'neutral',   note: 'Chief’s baraza raised water rationing; wants a clear plan to share with residents.', when: '2h' },
  { id: 'n2', circle: 'Community leaders', area: 'Mkomani',           mood: 'praise',    note: 'Elders happy with the youth event; asked for one more before campaigns peak.', when: '6h' },
  { id: 'n3', circle: 'Warembo',           area: 'Kadzandani',        mood: 'praise',    note: 'Good turnout at the women’s group meeting; mobilization is strong here.', when: '8h' },
  { id: 'n4', circle: 'Alfayo Flames',     area: 'Frere Town',        mood: 'criticism', note: 'Ground team reports opponent posters going up fast; we are behind on visibility.', when: '1d' },
  { id: 'n5', circle: 'Members',           area: 'Ziwa La Ng’ombe', mood: 'criticism', note: 'Members flag drainage complaints rising after the rains.', when: '1d' },
];

// Opponent watch — share of voice + tone (illustrative, not measured).
export interface Opponent {
  id: string;
  name: string;
  tag: string;
  shareOfVoice: number;    // % of total candidate conversation
  sentiment: SentimentSplit;
  topLine: string;         // what they're pushing this week
}

export const OPPONENTS: Opponent[] = [
  { id: 'o1', name: 'Said Abdalla', tag: 'SAIDO',  shareOfVoice: 22, sentiment: { praise: 48, neutral: 34, criticism: 18 }, topLine: 'Development promises; most active opponent this week.' },
  { id: 'o2', name: 'Abdulswamad Ali', tag: 'AA',  shareOfVoice: 9,  sentiment: { praise: 40, neutral: 45, criticism: 15 }, topLine: 'Low volume; occasional posts on infrastructure.' },
  { id: 'o3', name: 'Abdikadir Dekow', tag: 'Dekow', shareOfVoice: 6, sentiment: { praise: 37, neutral: 49, criticism: 14 }, topLine: 'Low volume; mostly reshares.' },
];

// Alfayo's own share of voice for the comparison (kept here so the bar totals read).
export const OUR_SHARE_OF_VOICE = 63; // %

// National threads touching Mombasa worth watching.
export const NATIONAL_THREADS: { id: string; topic: string; note: string; heat: 'rising' | 'steady' | 'cooling' }[] = [
  { id: 't1', topic: 'Port & jobs debate',     note: 'National jobs conversation spilling into local chatter; relevant to youth message.', heat: 'rising' },
  { id: 't2', topic: 'County service delivery', note: 'Ongoing background theme; occasionally invoked in complaints.', heat: 'steady' },
];

// Source connection status — drives the "Sources" tab and the honest banner.
export interface SourceStatus {
  source: Source;
  label: string;
  status: 'connected' | 'pending' | 'not_connected' | 'restricted';
  note: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// ACCOUNTS — the real public handles being monitored (candidate + opponents).
// These links ARE real (provided by the campaign). The metrics/quotes tied to
// them elsewhere in this file are still placeholder until ingestion is wired.
// ─────────────────────────────────────────────────────────────────────────────
export interface AccountLink {
  platform: Source;
  url: string;
}
export interface MonitoredFigure {
  id: string;
  name: string;
  tag: string;
  side: 'ours' | 'opponent';
  accounts: AccountLink[];
  note?: string; // e.g. data-quality flags
}

export const MONITORED_FIGURES: MonitoredFigure[] = [
  {
    id: 'alfayo', name: 'Alfayo Nelson', tag: 'ALFAYO', side: 'ours',
    accounts: [
      { platform: 'facebook',  url: 'https://www.facebook.com/share/1DCU9qvPyv/' },
      { platform: 'instagram', url: 'https://www.instagram.com/alfayo_kato' },
      { platform: 'tiktok',    url: 'https://www.tiktok.com/@hon.nelsonalfayo' },
      { platform: 'tiktok',    url: 'https://www.tiktok.com/@hon.alfayo.digita' },
    ],
  },
  {
    id: 'saido', name: 'Said Abdalla', tag: 'SAIDO', side: 'opponent',
    accounts: [
      { platform: 'facebook', url: 'https://www.facebook.com/share/1BYjJdKTh8/' },
      { platform: 'tiktok',   url: 'https://www.tiktok.com/@hon.saidabdallasalim' },
    ],
  },
  {
    id: 'aa', name: 'Abdulswamad Ali', tag: 'AA', side: 'opponent',
    accounts: [
      { platform: 'facebook', url: 'https://www.facebook.com/share/1BYjJdKTh8/' },
      { platform: 'tiktok',   url: 'https://www.tiktok.com/@hon.saidabdallasalim' },
    ],
    note: '⚠️ AA’s Facebook & TikTok links appear identical to SAIDO’s — likely a copy-paste mix-up. Please confirm AA’s real handles before we monitor.',
  },
  {
    id: 'dekow', name: 'Abdikadir Dekow', tag: 'Dekow', side: 'opponent',
    accounts: [
      { platform: 'facebook', url: 'https://www.facebook.com/share/1DrFqrRNCn/' },
      { platform: 'tiktok',   url: 'https://vt.tiktok.com/ZSXUNs9Yf/' },
    ],
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// DAILY REPORT — regenerated nightly at 00:00 (midnight) EAT.
//
// Per platform, a ranked "case" (most important → least). Each point has a short
// headline for the in-app view and a wordy `detail` paragraph for the PDF, so the
// download builds the argument while the screen stays scannable.
// ─────────────────────────────────────────────────────────────────────────────
export const REPORT_SCHEDULE = {
  cron: '0 0 * * *',           // 00:00 daily
  timezone: 'Africa/Nairobi',  // EAT (UTC+3)
  label: 'Auto-refreshes daily at 12:00 midnight (EAT)',
};

export interface CasePoint {
  rank: number;
  weight: 'high' | 'medium' | 'low';
  sentiment: Sentiment;
  point: string;      // short — in-app
  detail: string;     // wordy — PDF
}

export interface PlatformReport {
  platform: Source;
  label: string;
  headline: string;
  sentiment: SentimentSplit;
  mentions: number;
  casePoints: CasePoint[];
}

export const PLATFORM_REPORTS: PlatformReport[] = [
  {
    platform: 'whatsapp', label: 'WhatsApp',
    headline: 'Ground groups are net-positive on presence but water complaints are hardening.',
    sentiment: { praise: 240, neutral: 150, criticism: 96 }, mentions: 486,
    casePoints: [
      { rank: 1, weight: 'high', sentiment: 'criticism', point: 'Water & drainage complaints organising in Ziwa La Ng’ombe groups',
        detail: 'Across ward WhatsApp groups the single most repeated grievance is water supply and post-rain drainage in Ziwa La Ng’ombe and parts of Frere Town. What makes this a priority rather than background noise is that residents are beginning to coordinate — sharing the same photos and tagging leaders — which is how a local grievance becomes a campaign liability. A concrete, dated response plan shared back into those groups would blunt it before opponents adopt it.' },
      { rank: 2, weight: 'high', sentiment: 'praise', point: '“He shows up” is the dominant positive, contrasted against absent rivals',
        detail: 'The strongest recurring praise is physical presence — cleanups, barazas, condolences. Members repeatedly frame it against opponents who “only appear during campaigns.” This is our most defensible advantage on WhatsApp and should be amplified with quick photo/video from every appearance, fed to members to reshare.' },
      { rank: 3, weight: 'medium', sentiment: 'praise', point: 'Youth-jobs message is landing with young members',
        detail: 'Younger members in Kongowea and Mkomani groups cite the youth programs as a real, tangible reason for support. This is a growth lane: pairing each event with a short “here’s who got placed” note would convert warm sentiment into shareable proof.' },
      { rank: 4, weight: 'low', sentiment: 'neutral', point: 'General “wait and see” caution among undecideds',
        detail: 'A steady undecided segment counsels patience — “let us see actions not talk.” Not hostile, but a reminder that promises without visible follow-through carry little weight here.' },
    ],
  },
  {
    platform: 'facebook', label: 'Facebook',
    headline: 'Positive engagement on events; opponents pushing development-promise counter-narrative.',
    sentiment: { praise: 190, neutral: 140, criticism: 78 }, mentions: 408,
    casePoints: [
      { rank: 1, weight: 'high', sentiment: 'praise', point: 'Event posts drawing strong positive reactions & shares',
        detail: 'Posts tied to community events consistently out-perform generic posts on reactions and shares, and the comment tone is warm. The takeaway: Facebook rewards concrete activity, not slogans — every event should become a post within hours while sentiment is hot.' },
      { rank: 2, weight: 'high', sentiment: 'criticism', point: 'SAIDO’s development-promise claim circulating in comments',
        detail: 'A specific development-promise claim associated with SAIDO is being reshared in comment threads under both his and neutral pages. Left unanswered it sets the frame. A calm, factual rebuttal — ideally with our own delivery record — is worth publishing this week.' },
      { rank: 3, weight: 'medium', sentiment: 'neutral', point: 'Roads in the interior raised as the deciding issue',
        detail: 'Several Frere Town commenters name interior roads as their single vote-deciding issue. This is a persuadable bloc: a clear position and any visible progress on that corridor would move them.' },
    ],
  },
  {
    platform: 'tiktok', label: 'TikTok',
    headline: 'Highest reach, youngest audience; tone is curious-neutral and highly swingable.',
    sentiment: { praise: 120, neutral: 180, criticism: 44 }, mentions: 344,
    casePoints: [
      { rank: 1, weight: 'high', sentiment: 'neutral', point: 'Widest reach but least committed — the persuasion frontier',
        detail: 'TikTok gives the largest raw reach and the youngest audience, but the tone is mostly curious-neutral rather than committed. That is exactly why it matters: this is where minds are still movable. Short, authentic clips (behind-the-scenes, youth voices) will do more here than polished ads.' },
      { rank: 2, weight: 'medium', sentiment: 'praise', point: 'Authentic “on the ground” clips outperform staged content',
        detail: 'The clips that travel are unpolished and real — the candidate actually present, doing something. Staged/formal content underperforms. Lean the content plan toward volume of authentic moments over production value.' },
      { rank: 3, weight: 'low', sentiment: 'criticism', point: 'Opponent short-form (esp. SAIDO) gaining traction',
        detail: 'SAIDO’s short-form is the most active among opponents and is picking up views. Not yet dominant, but worth a consistent posting cadence from our two accounts so we are not out-posted on the platform with the most undecideds.' },
    ],
  },
  {
    platform: 'instagram', label: 'Instagram',
    headline: 'Smaller but warm audience; strongest on women-group and community-support content.',
    sentiment: { praise: 62, neutral: 40, criticism: 23 }, mentions: 125,
    casePoints: [
      { rank: 1, weight: 'medium', sentiment: 'praise', point: 'Women-group & welfare support resonates most',
        detail: 'The best-received Instagram content centres on women’s groups and welfare support, with appreciative comments. Smaller audience than TikTok/Facebook, but high-trust — a good channel to deepen loyalty with the women’s vote rather than chase raw reach.' },
      { rank: 2, weight: 'low', sentiment: 'neutral', point: 'Consistency, not volume, is the current gap',
        detail: 'Engagement is fine when we post; the issue is cadence. A simple twice-weekly rhythm would compound the warm base already there.' },
    ],
  },
];

export const SOURCE_STATUS: SourceStatus[] = [
  { source: 'whatsapp',  label: 'WhatsApp',  status: 'not_connected', note: 'Needs a decision on approach (official campaign number + member intake recommended). Group reading is not available via the official API.' },
  { source: 'facebook',  label: 'Facebook',  status: 'pending',       note: 'Alfayo’s own Page can connect via a Page token he authorizes (comments, reactions, feedback). Opponent pages need a listening tool.' },
  { source: 'instagram', label: 'Instagram', status: 'pending',       note: 'Alfayo’s own IG (business/creator) can connect via Graph API. Others need a listening tool.' },
  { source: 'tiktok',    label: 'TikTok',    status: 'pending',       note: 'Own accounts via TikTok API (limited). Opponent monitoring needs manual/periodic collection or a listening tool.' },
  { source: 'x',         label: 'X / Twitter', status: 'not_connected', note: 'Optional. Add if it becomes a relevant channel in Nyali.' },
];
